from .base_path import BasePath
from popcornn.tools import Images, wrap_positions


class LinearPath(BasePath):
    """
    Linear path class for generating linear interpolation paths.
    """
    def __init__(self, unwrap_positions, **kwargs):
        super().__init__(**kwargs)
        self.vec = self.final_position - self.initial_position
        if unwrap_positions and self.transform:
            print("Unwrapping positions for linear path. Assuming no atoms move more than half the box length.")
            self.vec = self.transform(self.vec, center=1.0)

    def get_positions(self, time: float):
        """
        Generates a geometric path using the MLP.

        Args:
            time (float): Time parameter for generating the path.
            *args: Additional arguments.

        Returns:
            torch.Tensor: The geometric path generated by the MLP.
        """
        return self.initial_position + time * self.vec